# Generated by Django 4.2 on 2024-11-22 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_movie_emenities_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
