# Generated by Django 4.2 on 2024-12-19 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_delete_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='emenities',
            new_name='emenitites',
        ),
    ]
