# Generated by Django 4.2 on 2024-12-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_rename_emenities_movie_emenitites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emenitites',
            new_name='Emenities',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='emenitites',
            new_name='menities',
        ),
    ]
