# Generated by Django 4.2 on 2024-12-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_rename_emenitites_emenities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='menities',
            new_name='emenities',
        ),
    ]
